# **🔢 Numpy**
  The NumPy library is the core library for scientific computing in Python. It provides a  high-performance multidimensional array object, and tools for working with these arrays.  

In [ ]:
#importing numpy
import numpy as np

if you want to add elements of two lists together like [1, 2, 3] + [1, 2, 3] = [2, 4, 6], doing this with regular lists will not works, the two lists will be concatenated not added mathimatically -- that's why we have Numpy, we can implement a huge number of mathematics operations on lists with Numpy!

In [ ]:
list1 = [1, 2, 3]
addition = list1 + list1  # wrong way to add two lists
addition

[1, 2, 3, 1, 2, 3]

In [ ]:
list1 = np.array([1, 2, 3])
list2 = np.array([1, 1, 1])
addition = list1 + list2  # right way to add two lists
addition

array([2, 3, 4])

**Creating arrays in numpy**

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
a = np.zeros((2, 3), dtype=np.int16)
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [ ]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

- What is the difference between '*arange*' and '*linespace*' ?

 =**np.arange:** generates values with a specified step size.

 =**np.linspace:** generates a specified number of evenly spaced values between two endpoints.

In [ ]:
a = np.arange(5, 25, 5)
a

array([ 5, 10, 15, 20])

In [ ]:
a = np.linspace(0, 1, 5)  #step = stop - start / elements - 1
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a = np.full((2,2),7) # constant array
a

array([[7, 7],
       [7, 7]])

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
a = np.random.rand(2,2)
a

NameError: name 'np' is not defined

How to create an array with random numbers?

1.   **np.random.rand(x, y):** randoms uniformly distributed between 0 and 1
2. **np.random.randint(start, stop, size = (x, y)):** random integers
3.   **np.random.uniform(start, stop, size = (x, y)):** random floats



In [ ]:
a = np.random.rand(2,2)
a

array([[0.66956227, 0.39063133],
       [0.22834178, 0.14719504]])

In [ ]:
a = np.random.randint(1,11, size = (2,2,3))
a

array([[[5, 5, 6],
        [9, 2, 2]],

       [[9, 6, 6],
        [4, 7, 6]]])

In [ ]:
a = np.random.uniform( size = (2,2))
a

**Creating 2D arrays**

In [ ]:
a_2d = np.array([[1, 2,3 ], 
                  [4, 5, 6],
                  [1, 2, 3],
                  [4, 5, 6],[1, 2,3 ], 
                  [4, 5, 6]])



In [ ]:
print(a_2d[0])

In [ ]:
a_2d.ndim

In [ ]:
a_2d.shape

In [ ]:
a_2d.size

In [ ]:
a_2d = np.arange(5, 25, 5).reshape(2,2)  # num of elements = stop - start / step
print(a_2d)

In [ ]:
a_2d = np.linspace(0, 1, 10).reshape(2,5)
a_2d

*Note that: methods like zeros and ones already takes dimenions so we do not need to use reshape with them*


**Arithmetic Operations**

In [ ]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

In [ ]:
res = np.add(a , b) #  or a + b
res

In [ ]:
res = np.subtract(a , b) #  or a - b
res

In [ ]:
res = np.divide(a , b) #  or a / b
res

In [ ]:
res = np.multiply(a , b) #  or a * b
res

In [ ]:
res = np.power(b, 2) # or b ** 2
res

In [ ]:
res = res = np.power(b, a)
res

In [ ]:
res = b ** a
print(res)

In [ ]:
x = [25, 9, 36]
res = np.sqrt(x)
res

In [ ]:
np.sqrt(b)

In [ ]:
res = np.dot(a, b) # a  @ b 
res

**Conditional Arithmetic**

In [ ]:
a = np.array([10, 15, 20, 25])
a[a>15] += 5
a

**Comparison Operations**

In [ ]:
a == b

In [ ]:
np.array_equal(a, b)

In [ ]:
a != b

In [ ]:
a > b

**Access Items in numpy arrays**

In [ ]:
a = np.array([10, 20, 30, 40])

In [ ]:
a[1] # access one item

In [ ]:
a[1:3] # access more than one sequential item using slicing

In [ ]:
a[::2] # access non-sequential items by defining step in slicing

In [ ]:
a[[0, 3, 2]] #access more than one item that are not sequential by their indexes using fancy indexing

In [ ]:
# Bolean indexing, example: even elements
x = np.array([1, 2, 3, 4])
bool_mask = x%2 == 0
x[bool_mask]

**Acessing 2d arrays**

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
a[0:1,1:2]

In [ ]:
a[1, 0]

In [ ]:
a[1][0] #same as a[1, 0]

In [ ]:
a[:2, 1:]  # access by slicing

In [ ]:
a[0 , 1:] # access by slicing

**Exercise 1: "Hot Day Finder"**

Tasks:

- Create a 4×7 matrix of random floats between 20 and 40 representing weekly temperatures for a month (4 weeks × 7 days).



- Create an array called weekdays containing day names in order:
['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']



- Use slicing to extract the last week's temperatures (last row of the matrix).

- Create a boolean mask identifying days where temperature exceeded 25°C in the last week.

- Apply this mask to the weekdays array to get names of hot days.


**Array Manipulation**

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2],
              [3, 4]])
0

In [ ]:
a = np.append(a,5) # add a new element
a

In [ ]:
b = np.append(b, [[5, 6]], axis = 0)
b

In [ ]:
b = np.append(b, [[0], [0], [0]], axis=1)
b

In [ ]:
a = np.insert(a,2,0) # add a new element in specific position > inseet(index, element)
a

In [ ]:
a = np.delete(a, 2)
a

what is the difference between resize and reshape?
> reshape does not change the data, if the elements of the new shape is larger or smaller than the original elements, an error will occur. but resize handle this.

In [ ]:
x= np.array([1, 2, 3, 4])
x=  np.resize(x, (2, 3))
x

The flatten() method in NumPy is used to convert a multi-dimensional array into a 1D array.

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a = a.flatten()
a

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a,b),axis=0)
c

**Aggregation Functions**

In [ ]:
a = np.array([0, 10, 30, 50, 10])
av = np.mean(a)
av

In [ ]:
med = np.median(a)
med

In [ ]:
standard = np.std(a)
standard

In [ ]:
total = np.sum(a)
total

In [ ]:
min = np.min(a)
min

In [ ]:
max = np.max(a)
max

##### `np.argmax()`  Find the Index of the Maximum Value
##### `np.argmin()`  Find the Index of the Minmum Value

`np.argmax()` is a NumPy function that returns the **index (position)** of the largest value in an array.
`np.argmin()` is a NumPy function that returns the **index (position)** of the lowest value in an array.


#### Syntax
```python
np.argmax(array)

In [ ]:
imin = np.argmin(a)
imin

In [ ]:
imax = np.argmax(a)
imax

**Conditions Using where**

**np.where():** It returns indices where a condition is True, or it can be used to choose values based on a condition (like an if-else for arrays).

In [ ]:
a = np.array([10, 20, 30, 40, 50])
indices = np.where(a > 25)

print(indices)
print(a[indices])
a[0]

In [ ]:
booll =a < 30
a[booll]

In [ ]:
b = np.array([1, 2, 3, 4, 5])
result = np.where(b % 2 == 0, 'even', 'odd')
print(result)

**Excercise 2: Sales Data Analysis**
- Create a 4×7 array of random sales between $100 and $500.

- Apply a 10% tax to sales exceeding $300. (x1.10)

- Use np.where() to give a 5% discount to sales below $200. (x 0.95)

- Find the average sales for weekends (last 2 columns).

- Identify days with sales > $400 (boolean mask).




`Solution:`

In [ ]:
sales = np.random.uniform(100, 500, (4, 7))
sales_with_tax = np.where(sales > 300, sales * 1.10, sales)
sales_final = np.where(sales_with_tax < 200, sales_with_tax * 0.95, sales_with_tax)
weekend_avg = sales_final[:, -2:].mean()
high_sales_mask = sales_final > 400

In [ ]:
high_sales_mask